-- vim.g.gruvbox_material_better_performance = 1
-- vim.g.gruvbox_material_transparent_background = 1
-- vim.g.gruvbox_material_diagnostic_virtual_text = 'colored'
-- vim.g.gruvbox_material_enable_bold = 1
-- vim.g.gruvbox_material_float_style = 'dim'
-- vim.g.gruvbox_material_colors_override = {
--    red = {'#FAA0A0', '167'},
--    green = {'#C1E1C1', '142'},
--    fg0 = {'#D2B48C', '223'},
--    aqua = {'#F8DE7E', '142'},
--    blue = {'#A7C7E7', '109'},
--    yellow = {'#FFFAA0', '214'},
--    orange = {'#F89880', '208'},
--    purple = {'#CF9FFF', '175'}
-- }
-- 
-- vim.cmd('colorscheme gruvbox-material')
