-- CUSTOM CONFIG
-- vim.highlight.priorities.semantic_tokens = 95
--
-- require('kanagawa').setup({
--   undercurl = true,
--   commentStyle = { italic = true },
--   functionStyle = { bold = true },
--   keywordStyle = { italic = false },
--   statementStyle = { bold = true },
--   typeStyle = {},
--   -- transparent = true,
--   dimInactive = false,
--   terminalColors = true,
--   theme = "dragon",
--   colors = {
--     palette = {
--       -- Muted blue tones for professional look
--       winterBlue = "#7A8CA3", -- More muted blue
--       crystalBlue = "#7E99A5", -- Desaturated crystal blue
--       springBlue = "#8199AD", -- Muted spring blue
--       waveBlue1 = "#414A5C", -- Deeper, more subtle wave blue
--
--       -- Desaturated warm colors for professional appearance
--       surimiOrange = "#B07D59", -- Muted, less saturated orange
--       carpYellow = "#B9A078", -- Desaturated yellow for professional look
--       sakuraPink = "#9D8C9A", -- Muted mauve for subtlety
--       peachRed = "#B57A7B",   -- Muted peach red
--       autumnRed = "#A66F71",  -- Desaturated autumn red
--       waveRed = "#A88188",    -- Muted wave red
--
--       -- Subdued green tones for professional environment
--       autumnGreen = "#879680", -- Muted, professional green
--       springGreen = "#9CA978", -- Desaturated olive-green
--       waveAqua1 = "#85A48D", -- Muted aqua for professional look
--
--       -- Subtle violet tones
--       oniViolet = "#8E889A",   -- Muted violet
--       springViolet1 = "#928B9E", -- Desaturated spring violet
--
--       -- Warm but professional background colors
--       sumiInk0 = "#1D1C1A", -- Deep, slightly warm background
--       sumiInk1 = "#282725", -- Subtle warm background
--       sumiInk2 = "#353431", -- Muted UI elements
--       sumiInk4 = "#54534D", -- Subtle accent for UI elements
--
--       -- Professional text colors with good readability
--       fujiWhite = "#E5DFD4", -- Slightly muted, warm white
--       oldWhite = "#C5BB9A", -- Muted secondary foreground
--       dragonBlue = "#7AA499", -- Muted teal for hints
--
--       -- Professional UI colors
--       selectionBg = "#3E4A5A", -- Muted selection background
--       popupBg = "#292825",   -- Subtle popup background
--       popupSel = "#45443D",  -- Muted selected item
--       menuBg = "#272623",    -- Subtle menu background
--       menuSelBg = "#3F3E38", -- Muted selected background
--
--       -- Subtle border colors
--       borderColor = "#54534D", -- Muted border color
--
--       -- Subtle scrollbar colors
--       scrollbarBg = "#2F2E2A",  -- Muted scrollbar background
--       scrollbarThumb = "#5A5952", -- Subtle scrollbar thumb
--     },
--     theme = {
--       dragon = {
--         ui = {
--           bg_gutter = "none" -- Transparent line number column
--         },
--         syn = {
--           parameter = "#A89985" -- Muted parameter color
--         }
--       },
--       all = {
--         ui = {
--           bg_p1 = "#282725", -- Subtle panel backgrounds
--           bg_p2 = "#353431", -- Slightly lighter panels
--           bg_gutter = 'none',
--           float = { bg = 'none' },
--         }
--       }
--     }
--   },
--   overrides = function(colors)
--     local palette = colors.palette
--     return {
--       -- Muted syntax highlighting for professional look
--       Boolean = { fg = palette.surimiOrange },
--       Number = { fg = palette.surimiOrange },
--       String = { fg = palette.springGreen },
--       Identifier = { fg = palette.fujiWhite },
--       Function = { fg = palette.carpYellow, bold = true },
--       Statement = { fg = palette.sakuraPink },
--       Keyword = { fg = palette.sakuraPink, italic = true },
--       Operator = { fg = palette.autumnRed },
--       Type = { fg = palette.waveAqua1 },
--
--       -- Subtle special elements
--       Special = { fg = palette.surimiOrange },
--       Comment = { fg = "#7A756F", italic = true }, -- Muted but readable comments
--
--       -- Subtle line numbers
--       LineNr = { fg = "#5A5A70" }, -- Muted line numbers
--       CursorLineNr = { fg = palette.oldWhite, bold = true },
--
--       -- Muted Tree-sitter integration
--       ["@keyword"] = { fg = palette.sakuraPink, italic = true },
--       ["@variable"] = { fg = palette.fujiWhite },
--       ["@variable.member"] = { fg = palette.waveAqua1 },
--       ["@function"] = { fg = palette.carpYellow, bold = true },
--       ["@property"] = { fg = palette.waveAqua1 },
--       ["@punctuation"] = { fg = palette.fujiWhite },
--       ["@constant"] = { fg = palette.surimiOrange },
--       ["@parameter"] = { fg = "#A89985" }, -- Muted parameter color
--       ["@variable.builtin"] = { fg = palette.autumnRed },
--       ["@this"] = { fg = palette.autumnRed },
--       ["@keyword.import"] = { fg = palette.autumnRed },
--       ["@include"] = { fg = palette.autumnRed },
--       ["@keyword.control.import"] = { fg = palette.autumnRed },
--
--       -- Subtle diagnostic colors
--       DiagnosticError = { fg = palette.peachRed },
--       DiagnosticWarn = { fg = palette.carpYellow },
--       DiagnosticInfo = { fg = palette.waveAqua1 },
--       DiagnosticHint = { fg = palette.dragonBlue },
--       FloatTitle = { bg = "none" },
--
--       -- Muted UI elements
--       Pmenu = { fg = palette.fujiWhite, bg = palette.popupBg },
--       PmenuSel = { fg = palette.fujiWhite, bg = palette.popupSel, bold = true },
--       PmenuSbar = { bg = palette.scrollbarBg },
--       PmenuThumb = { bg = palette.scrollbarThumb },
--
--       -- Subtle selection
--       Visual = { bg = palette.selectionBg },
--       VisualNOS = { bg = palette.selectionBg },
--
--       -- Muted search highlighting
--       Search = { fg = palette.sumiInk0, bg = palette.waveAqua1, bold = false },
--       IncSearch = { fg = palette.sumiInk0, bg = palette.carpYellow, bold = true },
--       CurSearch = { fg = palette.sumiInk0, bg = palette.carpYellow, bold = true },
--
--       -- Subtle cursor line
--       Cursor = { fg = palette.sumiInk0, bg = palette.fujiWhite },
--       CursorLine = { bg = "#2F2E2A" }, -- Subtle cursor line
--
--       -- Muted fold column
--       Folded = { fg = palette.fujiWhite, bg = "#363532" },
--       FoldColumn = { fg = palette.sumiInk4, bg = "NONE" },
--
--       -- Subtle status line
--       StatusLine = { fg = palette.oldWhite, bg = "#363532" },
--       StatusLineNC = { fg = palette.fujiWhite, bg = "#2D2C28" },
--
--       -- Muted tab line
--       TabLine = { fg = palette.fujiWhite, bg = "#2D2C28" },
--       TabLineSel = { fg = palette.oldWhite, bg = "#3F3E38", bold = true },
--       TabLineFill = { bg = "#292827" },
--
--       -- Subtle split dividers
--       VertSplit = { fg = palette.borderColor, bg = "NONE" },
--
--       -- Muted floating windows
--       NormalFloat = { fg = palette.fujiWhite, bg = 'none' },
--       FloatBorder = { fg = palette.borderColor, bg = 'none' },
--
--       -- Subtle diff highlighting
--       DiffAdd = { bg = "#3D4940" },
--       DiffChange = { bg = "#3D4752" },
--       DiffDelete = { bg = "#4D383C" },
--       DiffText = { bg = "#45503C" },
--
--       -- Muted completion
--       CmpItemAbbr = { fg = palette.fujiWhite },
--       CmpItemAbbrMatch = { fg = palette.carpYellow, bold = true },
--       CmpItemAbbrMatchFuzzy = { fg = palette.carpYellow, bold = true },
--       CmpItemKind = { fg = palette.springBlue },
--       CmpItemMenu = { fg = palette.springViolet1 },
--
--       -- Subtle Nvim-tree
--       NvimTreeNormal = { fg = palette.fujiWhite, bg = 'none' },
--       NvimTreeEndOfBuffer = { fg = palette.sumiInk1, bg = 'none' },
--       NvimTreeFolderName = { fg = palette.springBlue },
--       NvimTreeOpenedFolderName = { fg = palette.springBlue, bold = true },
--
--       -- Muted Telescope
--       TelescopeMatching = { fg = palette.carpYellow, bold = true },
--       TelescopeNormal = { bg = 'none' },
--       TelescopeBorder = { fg = palette.borderColor, bg = 'none' },
--       TelescopeSelection = { fg = palette.fujiWhite, bg = palette.popupSel },
--       TelescopePromptPrefix = { fg = palette.surimiOrange },
--
--       -- Subtle LSP
--       LspReferenceText = { bg = "#3F3E38" },
--       LspReferenceRead = { bg = "#3F3E38" },
--       LspReferenceWrite = { bg = "#3F3E38" },
--       LspSignatureActiveParameter = { fg = palette.carpYellow, bold = true },
--
--       -- Muted diagnostics floating
--       DiagnosticFloatingError = { fg = palette.peachRed },
--       DiagnosticFloatingWarn = { fg = palette.carpYellow },
--       DiagnosticFloatingInfo = { fg = palette.waveAqua1 },
--       DiagnosticFloatingHint = { fg = palette.dragonBlue },
--
--       -- Subtle indent-blankline
--       IndentBlanklineChar = { fg = "#3F3E38" },
--       IndentBlanklineContextChar = { fg = "#5A5952" },
--     }
--   end,
--   background = {
--     dark = "dragon",
--     light = "lotus",
--   },
-- })

-- Apply the colorscheme
-- vim.cmd("colorscheme kanagawa")
