-- local default_colors = require('kanagawa.colors').setup()
-- 
-- require('kanagawa').setup({
--     undercurl = false,
--     keywordStyle = { italic = false },
--     statementStyle = { bold = false },
--     variablebuiltinStyle = { italic = false },
--     transparent = true,
--     colors = {
--       sumiInk3 = default_colors.sumiInk1,
--     },
-- })
-- 
-- vim.cmd("colorscheme kanagawa")
